/* hw_suite -- console correctness suites: job generation and comparison (console vs model vs reference).
 *
 *   hw_suite gen vendor       tests/hw/vendor/jobs.txt: every vendor bin at 0, stub at 0x1FE000, the 0xDEADBEEF
 *                             end word patched to "b 0x1FE000"; reads the stub's result block.
 *   hw_suite gen qemu_diff    tests/hw/qemu_diff/jobs.txt: every tests/qemu_diff/s* batch linked at 0x10000
 *                             (built to ../build/hw/qemu_diff/), vectors 0x00 -> 0x10000, 0x04..0x1C -> stub entry;
 *                             reads the result block, out_tab and scratch.
 *   hw_suite check vendor     console r1 (failure bits) and pass/fail next to the model's
 *   hw_suite check qemu_diff  console out_tab/scratch vs qemu's expected.bin (and the model), per case
 *   hw_suite gen|check mulsem multiplier semantics (hw/arm/k_mulsem.s): MLA Rd == Rm, MUL(S)/MLA(S) flags, against the
 *                             model's 2-bit Booth datapath under each MUL carry hypothesis
 * Then ./run_hw.sh vendor / ./run_hw.sh qemu_diff between gen and check.  Run from wren7-rtl/model.
 *
 * Registers the tests do not write keep their values across ARM resets on the console (tests/hw/bringup), so only
 * what a test defines is compared.
 */
#include "hwjob.h"
#include <dirent.h>
#include <algorithm>
#include <map>

using namespace wren7;

static const uint32_t STUB = 0x1FE000, RES = 0x1FF000, RESLEN = 0x60;

static std::string tool(const char *t)
{
    const char *b = getenv("DC_ARM_BIN");
    return std::string(b ? b : "/opt/toolchains/dc-dca3/arm-eabi/bin") + "/arm-eabi-" + t;
}
static bool sh(const std::string &c)
{
    int rc = system(c.c_str());
    if (rc) fprintf(stderr, "failed (%d): %s\n", rc, c.c_str());
    return rc == 0;
}
static uint32_t branch(uint32_t from, uint32_t to) { return 0xEA000000u | (((to - from - 8) >> 2) & 0xFFFFFF); }
static uint32_t le32(const uint8_t *p) { return p[0] | (p[1] << 8) | (p[2] << 16) | ((uint32_t)p[3] << 24); }

static std::vector<std::string> list_dir(const std::string &d, const std::string &suffix, char first = 0)
{
    std::vector<std::string> v;
    if (DIR *dd = opendir(d.c_str())) {
        while (dirent *e = readdir(dd)) {
            std::string n = e->d_name;
            if (first && n[0] != first) continue;
            if (n.size() >= suffix.size() && n.compare(n.size() - suffix.size(), suffix.size(), suffix) == 0) v.push_back(n);
        }
        closedir(dd);
    }
    std::sort(v.begin(), v.end());
    return v;
}

static const std::string VBINS = "../vendor/arm7di-tests-dreamcast/bins";

static int gen_vendor()
{
    if (!sh("mkdir -p tests/hw/vendor/hw")) return 2;
    FILE *jf = fopen("tests/hw/vendor/jobs.txt", "w");
    fprintf(jf, "# generated by tools/hw_suite gen vendor -- vendor/arm7di-tests-dreamcast on the console\nout tests/hw/vendor/hw\n");
    for (auto &n : list_dir(VBINS, ".bin")) {
        std::vector<uint8_t> img;
        read_all(VBINS + "/" + n, img);
        uint32_t end = 0xFFFFFFFF;
        for (uint32_t a = 0; a + 4 <= img.size(); a += 4)
            if (le32(&img[a]) == 0xDEADBEEF) { end = a; break; }
        if (end == 0xFFFFFFFF) { fprintf(stderr, "%s: no 0xDEADBEEF\n", n.c_str()); continue; }
        const std::string t = n.substr(0, n.find(".s.bin"));
        fprintf(jf, "job %s 500 1\nload 0 %s/%s\nload 0x%X ../build/hw/arm/stub.bin\nword 0x%X 0x%08X\nread 0x%X 0x%X\nrun\n",
                t.c_str(), VBINS.c_str(), n.c_str(), STUB, end, branch(end, STUB), RES, RESLEN);
    }
    fclose(jf);
    printf("wrote tests/hw/vendor/jobs.txt\n");
    return 0;
}

struct Batch { std::string name; uint32_t out_tab = 0, scratch = 0, in_tab = 0; size_t ncases = 0; int regions = 0; };

static bool batch_info(const std::string &name, Batch &b)
{
    b.name = name;
    const std::string sym = "../build/hw/qemu_diff/" + name + ".sym";
    FILE *f = fopen(sym.c_str(), "r");
    if (!f) return false;
    char line[256];
    while (fgets(line, sizeof line, f)) {
        unsigned a;
        char t, nm[128];
        if (sscanf(line, "%x %c %127s", &a, &t, nm) != 3) continue;
        if (!strcmp(nm, "out_tab")) b.out_tab = a;
        if (!strcmp(nm, "scratch")) b.scratch = a;
        if (!strcmp(nm, "in_tab")) b.in_tab = a;
    }
    fclose(f);
    FILE *c = fopen(("tests/qemu_diff/" + name + "/cases.tsv").c_str(), "r");
    if (!c) return false;
    while (fgets(line, sizeof line, c)) {
        int idx, region;
        char cls[32];
        unsigned op, mask;
        if (line[0] == '#' || sscanf(line, "%d %31s %x %x %d", &idx, cls, &op, &mask, &region) != 5) continue;
        b.ncases++;
        b.regions = std::max(b.regions, region + 1);
    }
    fclose(c);
    return b.out_tab && b.scratch;
}

static int gen_qemu_diff()
{
    if (!sh("mkdir -p tests/hw/qemu_diff/hw ../build/hw/qemu_diff")) return 2;
    FILE *jf = fopen("tests/hw/qemu_diff/jobs.txt", "w");
    fprintf(jf, "# generated by tools/hw_suite gen qemu_diff -- tests/qemu_diff batches on the console\nout tests/hw/qemu_diff/hw\n");
    for (auto &name : list_dir("tests/qemu_diff", "", 's')) {
        const std::string o = "../build/hw/qemu_diff/" + name;
        if (!sh(tool("as") + " -mcpu=arm7 tests/qemu_diff/" + name + "/prog.s -o " + o + ".o")) return 2;
        if (!sh(tool("ld") + " -Ttext=0x10000 -z max-page-size=0x1000 -e _start --no-warn-rwx-segments -o " + o +
                ".elf " + o + ".o"))
            return 2;
        if (!sh(tool("objcopy") + " -O binary " + o + ".elf " + o + ".bin")) return 2;
        if (!sh(tool("nm") + " " + o + ".elf > " + o + ".sym")) return 2;
        Batch b;
        if (!batch_info(name, b)) { fprintf(stderr, "%s: no symbols/cases\n", name.c_str()); return 2; }
        fprintf(jf, "job %s 3000 1\nload 0x10000 %s.bin\nload 0x%X ../build/hw/arm/stub.bin\nword 0 0x%08X\n", name.c_str(),
                o.c_str(), STUB, branch(0, 0x10000));
        for (uint32_t k = 1; k < 8; k++) fprintf(jf, "word 0x%X 0x%08X\n", 4 * k, branch(4 * k, STUB + 16 * k));
        fprintf(jf, "read 0x%X 0x%X\nread 0x%X 0x%zX\nread 0x%X 0x%X\nrun\n", RES, RESLEN, b.out_tab, b.ncases * 64,
                b.scratch, (unsigned)b.regions * 128);
    }
    fclose(jf);
    printf("wrote tests/hw/qemu_diff/jobs.txt\n");
    return 0;
}

static std::map<std::string, std::string> read_status(const std::string &p)
{
    std::map<std::string, std::string> m;
    FILE *f = fopen(p.c_str(), "r");
    if (!f) return m;
    char line[512], n[128], s[32];
    while (fgets(line, sizeof line, f))
        if (sscanf(line, "%127s %31s", n, s) == 2) m[n] = s;
    fclose(f);
    return m;
}

static int check_vendor()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/vendor/jobs.txt", jf)) return 2;
    auto st = read_status("tests/hw/vendor/hw/results.txt");
    FILE *out = fopen("tests/hw/vendor/SUMMARY.txt", "w");
    int agree = 0, n = 0;
    for (auto &j : jf.jobs) {
        std::vector<uint8_t> hw;
        const bool have = read_all("tests/hw/vendor/hw/" + j.name + ".bin", hw) && hw.size() >= RESLEN;
        ModelRun m = run_job_model(j, DcWaits());
        const uint32_t hr1 = have ? le32(&hw[8 + 4]) : 0, mr1 = le32(&m.readback[8 + 4]);
        const uint32_t hk = have ? le32(&hw[4]) : 99, mk = le32(&m.readback[4]);
        const bool hpass = have && st[j.name] == "done" && le32(&hw[0]) == 0x454E4F44 && hk == 0 && !(hr1 & 0x3FFFFFFF);
        const bool mpass = m.done && mk == 0 && !(mr1 & 0x3FFFFFFF);
        const bool same = have && hr1 == mr1 && hk == mk;
        agree += same;
        n++;
        char line[256];
        snprintf(line, sizeof line, "%-10s console %-4s r1=%08x exit=%u | model %-4s r1=%08x exit=%u  %s\n", j.name.c_str(),
                 hpass ? "PASS" : "FAIL", hr1, hk, mpass ? "PASS" : "FAIL", mr1, mk, same ? "same" : "DIFFERENT");
        fputs(line, stdout);
        fputs(line, out);
    }
    char line[128];
    snprintf(line, sizeof line, "%d/%d tests: console and model agree on r1 and the exit path\n", agree, n);
    fputs(line, stdout);
    fputs(line, out);
    fclose(out);
    return agree == n ? 0 : 1;
}

static int check_qemu_diff()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/qemu_diff/jobs.txt", jf)) return 2;
    auto st = read_status("tests/hw/qemu_diff/hw/results.txt");
    FILE *out = fopen("tests/hw/qemu_diff/SUMMARY.txt", "w");
    int bad_total = 0;
    for (auto &j : jf.jobs) {
        Batch b;
        batch_info(j.name, b);
        std::vector<uint8_t> hw, ref, cases_txt;
        const bool have = read_all("tests/hw/qemu_diff/hw/" + j.name + ".bin", hw);
        read_all("tests/qemu_diff/" + j.name + "/expected.bin", ref);
        ModelRun m = run_job_model(j, DcWaits());
        std::vector<uint32_t> masks, regions, ops;
        {
            FILE *c = fopen(("tests/qemu_diff/" + j.name + "/cases.tsv").c_str(), "r");
            char line[256];
            while (fgets(line, sizeof line, c)) {
                int idx, region;
                char cls[32];
                unsigned op, mask;
                if (line[0] == '#' || sscanf(line, "%d %31s %x %x %d", &idx, cls, &op, &mask, &region) != 5) continue;
                masks.push_back(mask);
                regions.push_back(region);
                ops.push_back(op);
            }
            fclose(c);
        }
        const size_t need = RESLEN + b.ncases * 64 + (size_t)b.regions * 128;
        if (!have || hw.size() != need || st[j.name] != "done" || le32(&hw[4]) != 2) {
            fprintf(out, "%s: console run incomplete (status %s, %zu bytes, exit vector %u)\n", j.name.c_str(),
                    st[j.name].c_str(), hw.size(), have && hw.size() >= 8 ? le32(&hw[4]) : 99);
            printf("%s: console run incomplete\n", j.name.c_str());
            bad_total++;
            continue;
        }
        int vs_ref = 0, vs_model = 0, shown = 0;
        for (size_t i = 0; i < b.ncases; i++) {
            const uint8_t *h = &hw[RESLEN + i * 64], *q = &ref[i * 64], *mm = &m.readback[RESLEN + i * 64];
            bool dr = false, dm = false;
            for (int k = 0; k < 15; k++) {
                const uint32_t mask = k == 14 ? masks[i] : 0xFFFFFFFF;
                if ((le32(h + 4 * k) & mask) != (le32(q + 4 * k) & mask)) dr = true;
                if ((le32(h + 4 * k) & mask) != (le32(mm + 4 * k) & mask)) dm = true;
            }
            if ((int)regions[i] >= 0) {
                const size_t off = RESLEN + b.ncases * 64 + (size_t)regions[i] * 128;
                const size_t qoff = b.ncases * 64 + (size_t)regions[i] * 128;
                if (memcmp(&hw[off], &ref[qoff], 128)) dr = true;
                if (memcmp(&hw[off], &m.readback[off], 128)) dm = true;
            }
            vs_ref += dr;
            vs_model += dm;
            if ((dr || dm) && shown++ < 10) {
                fprintf(out, "%s case %zu op=%08x:%s%s\n", j.name.c_str(), i, ops[i], dr ? " differs from qemu" : "",
                        dm ? " differs from model" : "");
                for (int k = 0; k < 15; k++)
                    if (le32(h + 4 * k) != le32(q + 4 * k) || le32(h + 4 * k) != le32(mm + 4 * k))
                        fprintf(out, "    word %2d console=%08x qemu=%08x model=%08x\n", k, le32(h + 4 * k), le32(q + 4 * k),
                                le32(mm + 4 * k));
            }
        }
        char line[256];
        snprintf(line, sizeof line, "%s: %zu cases, console vs qemu %d mismatches, console vs model %d mismatches\n",
                 j.name.c_str(), b.ncases, vs_ref, vs_model);
        fputs(line, stdout);
        fputs(line, out);
        bad_total += vs_ref + vs_model;
    }
    fclose(out);
    return bad_total ? 1 : 0;
}

/* ---- mulsem: multiplier semantics (MLA Rd == Rm, MUL(S)/MLA(S) flags) ---- */
static const unsigned MS_N = 1024;

static int gen_mulsem()
{
    if (!sh("mkdir -p tests/hw/mulsem/hw")) return 2;
    std::vector<uint8_t> in;
    uint64_t x = 0x9E3779B97F4A7C15ull;
    auto rnd = [&]() { x ^= x << 13; x ^= x >> 7; x ^= x << 17; return (uint32_t)(x >> 16); };
    static const uint32_t sp[] = {0, 1, 2, 3, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0xFFFFFFFE, 0x55555555, 0xAAAAAAAA,
                                  0x10000, 0xFFFF, 0x80, 0x7F, 0x12345678};
    for (unsigned i = 0; i < MS_N; i++) {
        uint32_t v[4];
        for (int k = 0; k < 3; k++) {
            const uint32_t c = rnd() % 5;
            v[k] = c == 0 ? sp[rnd() % 15] : c == 1 ? (rnd() & 0xFF) : c == 2 ? (1u << (rnd() & 31)) : rnd();
        }
        v[3] = rnd() & 0xF0000000u;
        for (int k = 0; k < 4; k++) for (int b = 0; b < 4; b++) in.push_back(v[k] >> (8 * b));
    }
    FILE *f = fopen("tests/hw/mulsem/inputs.bin", "wb");
    fwrite(in.data(), 1, in.size(), f);
    fclose(f);
    f = fopen("tests/hw/mulsem/jobs.txt", "w");
    fprintf(f, "# generated by tools/hw_suite gen mulsem -- multiplier semantics (hw/arm/k_mulsem.s)\n"
               "out tests/hw/mulsem/hw\njob mulsem 2000 1\nload 0 ../build/hw/arm/k_mulsem.bin\n"
               "load 0x%X ../build/hw/arm/stub.bin\nload 0x20000 tests/hw/mulsem/inputs.bin\nword 0x20 %u\n"
               "read 0x%X 0x%X\nread 0x30000 0x%X\nrun\n", STUB, MS_N, RES, RESLEN, MS_N * 24);
    fclose(f);
    printf("wrote tests/hw/mulsem/jobs.txt and inputs.bin\n");
    return 0;
}

static int check_mulsem()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/mulsem/jobs.txt", jf) || jf.jobs.empty()) return 2;
    std::vector<uint8_t> hw, in;
    if (!read_all("tests/hw/mulsem/hw/mulsem.bin", hw) || hw.size() != RESLEN + MS_N * 24) { fprintf(stderr, "no console result\n"); return 2; }
    read_all("tests/hw/mulsem/inputs.bin", in);
    FILE *out = fopen("tests/hw/mulsem/SUMMARY.txt", "w");
    static const char *field[6] = {"MLA Rd==Rm", "MULS result", "MULS CPSR", "MLAS result", "MLAS CPSR", "MULS Rd==Rm"};
    static const char *mc[3] = {"C kept", "C = last ALU carry", "C = last shifter carry"};
    int best = 1 << 30;
    for (int c = 0; c < 3; c++) {
        ModelRun m = run_job_model(jf.jobs[0], DcWaits(), 400000000ull, nullptr, c);
        int bad[6] = {0};
        int shown = 0;
        for (unsigned i = 0; i < MS_N; i++)
            for (int k = 0; k < 6; k++) {
                const size_t o = RESLEN + i * 24 + 4 * k;
                const uint32_t mask = (k == 2 || k == 4) ? 0xF0000000u : 0xFFFFFFFFu;
                const uint32_t hv = le32(&hw[o]) & mask, mv = le32(&m.readback[o]) & mask;
                if (hv != mv) {
                    bad[k]++;
                    if (shown++ < 6)
                        fprintf(out, "  [%s] rec %u %s: Rm=%08x Rs=%08x Rn=%08x flags=%x console=%08x model=%08x\n", mc[c], i,
                                field[k], le32(&in[16 * i]), le32(&in[16 * i + 4]), le32(&in[16 * i + 8]),
                                le32(&in[16 * i + 12]) >> 28, hv, mv);
                }
            }
        char line[512];
        snprintf(line, sizeof line, "%-24s mismatches over %u records: %s %d, %s %d, %s %d, %s %d, %s %d, %s %d\n", mc[c],
                 MS_N, field[0], bad[0], field[1], bad[1], field[2], bad[2], field[3], bad[3], field[4], bad[4], field[5], bad[5]);
        fputs(line, stdout);
        fputs(line, out);
        int tot = 0;
        for (int k = 0; k < 6; k++) tot += bad[k];
        best = std::min(best, tot);
    }
    fclose(out);
    return best ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "mulsem")) return gen_mulsem();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "mulsem")) return check_mulsem();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "vendor")) return gen_vendor();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "qemu_diff")) return gen_qemu_diff();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "vendor")) return check_vendor();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "qemu_diff")) return check_qemu_diff();
    fprintf(stderr, "usage: hw_suite gen|check vendor|qemu_diff|mulsem   (from wren7-rtl/model)\n");
    return 2;
}
