/* hw_suite -- console correctness suites: job generation and comparison (console vs model vs reference).
 *
 *   hw_suite gen vendor       tests/hw/vendor/jobs.txt: every vendor bin at 0, stub at 0x1FE000, the 0xDEADBEEF
 *                             end word patched to "b 0x1FE000"; reads the stub's result block.
 *   hw_suite gen qemu_diff    tests/hw/qemu_diff/jobs.txt: every tests/qemu_diff/s* batch linked at 0x10000
 *                             (built to ../build/hw/qemu_diff/), vectors 0x00 -> 0x10000, 0x04..0x1C -> stub entry;
 *                             reads the result block, out_tab and scratch.
 *   hw_suite check vendor     console r1 (failure bits) and pass/fail next to the model's
 *   hw_suite check qemu_diff  console out_tab/scratch vs qemu's expected.bin (and the model), per case
 *   hw_suite check dspport    DSP TEMP writes vs the ARM's TEMP reads (hw/arm/k_dspport*.s), adds per sample
 *   hw_suite check blkshot    single-shot FIQ-timed probes (hw/arm/k_blkshot*.s)
 *   hw_suite check dspmem[1]  ARM timing kernels while the DSP accesses wave RAM (hw/arm/k_dspmem_*.s)
 *   hw_suite check sgc        the same kernels while sound channels play (sgcadp: ADPCM channels)
 *   hw_suite check sh4load T  ... while the SH4 accesses G2 (model: SH4 stream generator, 8 phases), tolerance T
 *   hw_suite check combo T    channels + DSP programs + SH4 writes together, tolerance T
 *   hw_suite check collide2 [DIR]  channel / DSP slot collisions, functional readouts: the console's, or those of
 *                             another AICA in DIR (caique-rtl rtl/v1 tb/armjob_tb -w DIR)
 *   hw_suite gen|check mulsem multiplier semantics (hw/arm/k_mulsem.s): MLA Rd == Rm, MUL(S)/MLA(S) flags, against the
 *                             model's 2-bit Booth datapath under each MUL carry hypothesis
 * Then ./run_hw.sh vendor / ./run_hw.sh qemu_diff between gen and check.  Run from wren7-rtl/model.
 *
 * Registers the tests do not write keep their values across ARM resets on the console (tests/hw/bringup), so only
 * what a test defines is compared.
 */
#include "hwjob.h"
#include <dirent.h>
#include <math.h>
#include <algorithm>
#include <map>

using namespace wren7;

static const uint32_t STUB = 0x1FE000, RES = 0x1FF000, RESLEN = 0x60;

static std::string tool(const char *t)
{
    const char *b = getenv("DC_ARM_BIN");
    return std::string(b ? b : "/opt/toolchains/dc-dca3/arm-eabi/bin") + "/arm-eabi-" + t;
}
static bool sh(const std::string &c)
{
    int rc = system(c.c_str());
    if (rc) fprintf(stderr, "failed (%d): %s\n", rc, c.c_str());
    return rc == 0;
}
static uint32_t branch(uint32_t from, uint32_t to) { return 0xEA000000u | (((to - from - 8) >> 2) & 0xFFFFFF); }
static uint32_t le32(const uint8_t *p) { return p[0] | (p[1] << 8) | (p[2] << 16) | ((uint32_t)p[3] << 24); }

static std::vector<std::string> list_dir(const std::string &d, const std::string &suffix, char first = 0)
{
    std::vector<std::string> v;
    if (DIR *dd = opendir(d.c_str())) {
        while (dirent *e = readdir(dd)) {
            std::string n = e->d_name;
            if (first && n[0] != first) continue;
            if (n.size() >= suffix.size() && n.compare(n.size() - suffix.size(), suffix.size(), suffix) == 0) v.push_back(n);
        }
        closedir(dd);
    }
    std::sort(v.begin(), v.end());
    return v;
}

static const std::string VBINS = "../vendor/arm7di-tests-dreamcast/bins";

static int gen_vendor()
{
    if (!sh("mkdir -p tests/hw/vendor/hw")) return 2;
    FILE *jf = fopen("tests/hw/vendor/jobs.txt", "w");
    fprintf(jf, "# generated by tools/hw_suite gen vendor -- vendor/arm7di-tests-dreamcast on the console\nout tests/hw/vendor/hw\n");
    for (auto &n : list_dir(VBINS, ".bin")) {
        std::vector<uint8_t> img;
        read_all(VBINS + "/" + n, img);
        uint32_t end = 0xFFFFFFFF;
        for (uint32_t a = 0; a + 4 <= img.size(); a += 4)
            if (le32(&img[a]) == 0xDEADBEEF) { end = a; break; }
        if (end == 0xFFFFFFFF) { fprintf(stderr, "%s: no 0xDEADBEEF\n", n.c_str()); continue; }
        const std::string t = n.substr(0, n.find(".s.bin"));
        fprintf(jf, "job %s 500 1\nload 0 %s/%s\nload 0x%X ../build/hw/arm/stub.bin\nword 0x%X 0x%08X\nread 0x%X 0x%X\nrun\n",
                t.c_str(), VBINS.c_str(), n.c_str(), STUB, end, branch(end, STUB), RES, RESLEN);
    }
    fclose(jf);
    printf("wrote tests/hw/vendor/jobs.txt\n");
    return 0;
}

struct Batch { std::string name; uint32_t out_tab = 0, scratch = 0, in_tab = 0; size_t ncases = 0; int regions = 0; };

static bool batch_info(const std::string &name, Batch &b)
{
    b.name = name;
    const std::string sym = "../build/hw/qemu_diff/" + name + ".sym";
    FILE *f = fopen(sym.c_str(), "r");
    if (!f) return false;
    char line[256];
    while (fgets(line, sizeof line, f)) {
        unsigned a;
        char t, nm[128];
        if (sscanf(line, "%x %c %127s", &a, &t, nm) != 3) continue;
        if (!strcmp(nm, "out_tab")) b.out_tab = a;
        if (!strcmp(nm, "scratch")) b.scratch = a;
        if (!strcmp(nm, "in_tab")) b.in_tab = a;
    }
    fclose(f);
    FILE *c = fopen(("tests/qemu_diff/" + name + "/cases.tsv").c_str(), "r");
    if (!c) return false;
    while (fgets(line, sizeof line, c)) {
        int idx, region;
        char cls[32];
        unsigned op, mask;
        if (line[0] == '#' || sscanf(line, "%d %31s %x %x %d", &idx, cls, &op, &mask, &region) != 5) continue;
        b.ncases++;
        b.regions = std::max(b.regions, region + 1);
    }
    fclose(c);
    return b.out_tab && b.scratch;
}

static int gen_qemu_diff()
{
    if (!sh("mkdir -p tests/hw/qemu_diff/hw ../build/hw/qemu_diff")) return 2;
    FILE *jf = fopen("tests/hw/qemu_diff/jobs.txt", "w");
    fprintf(jf, "# generated by tools/hw_suite gen qemu_diff -- tests/qemu_diff batches on the console\nout tests/hw/qemu_diff/hw\n");
    for (auto &name : list_dir("tests/qemu_diff", "", 's')) {
        const std::string o = "../build/hw/qemu_diff/" + name;
        if (!sh(tool("as") + " -mcpu=arm7 tests/qemu_diff/" + name + "/prog.s -o " + o + ".o")) return 2;
        if (!sh(tool("ld") + " -Ttext=0x10000 -z max-page-size=0x1000 -e _start --no-warn-rwx-segments -o " + o +
                ".elf " + o + ".o"))
            return 2;
        if (!sh(tool("objcopy") + " -O binary " + o + ".elf " + o + ".bin")) return 2;
        if (!sh(tool("nm") + " " + o + ".elf > " + o + ".sym")) return 2;
        Batch b;
        if (!batch_info(name, b)) { fprintf(stderr, "%s: no symbols/cases\n", name.c_str()); return 2; }
        fprintf(jf, "job %s 3000 1\nload 0x10000 %s.bin\nload 0x%X ../build/hw/arm/stub.bin\nword 0 0x%08X\n", name.c_str(),
                o.c_str(), STUB, branch(0, 0x10000));
        for (uint32_t k = 1; k < 8; k++) fprintf(jf, "word 0x%X 0x%08X\n", 4 * k, branch(4 * k, STUB + 16 * k));
        fprintf(jf, "read 0x%X 0x%X\nread 0x%X 0x%zX\nread 0x%X 0x%X\nrun\n", RES, RESLEN, b.out_tab, b.ncases * 64,
                b.scratch, (unsigned)b.regions * 128);
    }
    fclose(jf);
    printf("wrote tests/hw/qemu_diff/jobs.txt\n");
    return 0;
}

static std::map<std::string, std::string> read_status(const std::string &p)
{
    std::map<std::string, std::string> m;
    FILE *f = fopen(p.c_str(), "r");
    if (!f) return m;
    char line[512], n[128], s[32];
    while (fgets(line, sizeof line, f))
        if (sscanf(line, "%127s %31s", n, s) == 2) m[n] = s;
    fclose(f);
    return m;
}

static int check_vendor()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/vendor/jobs.txt", jf)) return 2;
    auto st = read_status("tests/hw/vendor/hw/results.txt");
    FILE *out = fopen("tests/hw/vendor/SUMMARY.txt", "w");
    int agree = 0, n = 0;
    for (auto &j : jf.jobs) {
        std::vector<uint8_t> hw;
        const bool have = read_all("tests/hw/vendor/hw/" + j.name + ".bin", hw) && hw.size() >= RESLEN;
        ModelRun m = run_job_model(j, DcWaits());
        const uint32_t hr1 = have ? le32(&hw[8 + 4]) : 0, mr1 = le32(&m.readback[8 + 4]);
        const uint32_t hk = have ? le32(&hw[4]) : 99, mk = le32(&m.readback[4]);
        const bool hpass = have && st[j.name] == "done" && le32(&hw[0]) == 0x454E4F44 && hk == 0 && !(hr1 & 0x3FFFFFFF);
        const bool mpass = m.done && mk == 0 && !(mr1 & 0x3FFFFFFF);
        const bool same = have && hr1 == mr1 && hk == mk;
        agree += same;
        n++;
        char line[256];
        snprintf(line, sizeof line, "%-10s console %-4s r1=%08x exit=%u | model %-4s r1=%08x exit=%u  %s\n", j.name.c_str(),
                 hpass ? "PASS" : "FAIL", hr1, hk, mpass ? "PASS" : "FAIL", mr1, mk, same ? "same" : "DIFFERENT");
        fputs(line, stdout);
        fputs(line, out);
    }
    char line[128];
    snprintf(line, sizeof line, "%d/%d tests: console and model agree on r1 and the exit path\n", agree, n);
    fputs(line, stdout);
    fputs(line, out);
    fclose(out);
    return agree == n ? 0 : 1;
}

static int check_qemu_diff()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/qemu_diff/jobs.txt", jf)) return 2;
    auto st = read_status("tests/hw/qemu_diff/hw/results.txt");
    FILE *out = fopen("tests/hw/qemu_diff/SUMMARY.txt", "w");
    int bad_total = 0;
    for (auto &j : jf.jobs) {
        Batch b;
        batch_info(j.name, b);
        std::vector<uint8_t> hw, ref, cases_txt;
        const bool have = read_all("tests/hw/qemu_diff/hw/" + j.name + ".bin", hw);
        read_all("tests/qemu_diff/" + j.name + "/expected.bin", ref);
        ModelRun m = run_job_model(j, DcWaits());
        std::vector<uint32_t> masks, regions, ops;
        {
            FILE *c = fopen(("tests/qemu_diff/" + j.name + "/cases.tsv").c_str(), "r");
            char line[256];
            while (fgets(line, sizeof line, c)) {
                int idx, region;
                char cls[32];
                unsigned op, mask;
                if (line[0] == '#' || sscanf(line, "%d %31s %x %x %d", &idx, cls, &op, &mask, &region) != 5) continue;
                masks.push_back(mask);
                regions.push_back(region);
                ops.push_back(op);
            }
            fclose(c);
        }
        const size_t need = RESLEN + b.ncases * 64 + (size_t)b.regions * 128;
        if (!have || hw.size() != need || st[j.name] != "done" || le32(&hw[4]) != 2) {
            fprintf(out, "%s: console run incomplete (status %s, %zu bytes, exit vector %u)\n", j.name.c_str(),
                    st[j.name].c_str(), hw.size(), have && hw.size() >= 8 ? le32(&hw[4]) : 99);
            printf("%s: console run incomplete\n", j.name.c_str());
            bad_total++;
            continue;
        }
        int vs_ref = 0, vs_model = 0, shown = 0;
        for (size_t i = 0; i < b.ncases; i++) {
            const uint8_t *h = &hw[RESLEN + i * 64], *q = &ref[i * 64], *mm = &m.readback[RESLEN + i * 64];
            bool dr = false, dm = false;
            for (int k = 0; k < 15; k++) {
                const uint32_t mask = k == 14 ? masks[i] : 0xFFFFFFFF;
                if ((le32(h + 4 * k) & mask) != (le32(q + 4 * k) & mask)) dr = true;
                if ((le32(h + 4 * k) & mask) != (le32(mm + 4 * k) & mask)) dm = true;
            }
            if ((int)regions[i] >= 0) {
                const size_t off = RESLEN + b.ncases * 64 + (size_t)regions[i] * 128;
                const size_t qoff = b.ncases * 64 + (size_t)regions[i] * 128;
                if (memcmp(&hw[off], &ref[qoff], 128)) dr = true;
                if (memcmp(&hw[off], &m.readback[off], 128)) dm = true;
            }
            vs_ref += dr;
            vs_model += dm;
            if ((dr || dm) && shown++ < 10) {
                fprintf(out, "%s case %zu op=%08x:%s%s\n", j.name.c_str(), i, ops[i], dr ? " differs from qemu" : "",
                        dm ? " differs from model" : "");
                for (int k = 0; k < 15; k++)
                    if (le32(h + 4 * k) != le32(q + 4 * k) || le32(h + 4 * k) != le32(mm + 4 * k))
                        fprintf(out, "    word %2d console=%08x qemu=%08x model=%08x\n", k, le32(h + 4 * k), le32(q + 4 * k),
                                le32(mm + 4 * k));
            }
        }
        char line[256];
        snprintf(line, sizeof line, "%s: %zu cases, console vs qemu %d mismatches, console vs model %d mismatches\n",
                 j.name.c_str(), b.ncases, vs_ref, vs_model);
        fputs(line, stdout);
        fputs(line, out);
        bad_total += vs_ref + vs_model;
    }
    fclose(out);
    return bad_total ? 1 : 0;
}

/* ---- mulsem: multiplier semantics (MLA Rd == Rm, MUL(S)/MLA(S) flags) ---- */
static const unsigned MS_N = 1024;

static int gen_mulsem()
{
    if (!sh("mkdir -p tests/hw/mulsem/hw")) return 2;
    std::vector<uint8_t> in;
    uint64_t x = 0x9E3779B97F4A7C15ull;
    auto rnd = [&]() { x ^= x << 13; x ^= x >> 7; x ^= x << 17; return (uint32_t)(x >> 16); };
    static const uint32_t sp[] = {0, 1, 2, 3, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0xFFFFFFFE, 0x55555555, 0xAAAAAAAA,
                                  0x10000, 0xFFFF, 0x80, 0x7F, 0x12345678};
    for (unsigned i = 0; i < MS_N; i++) {
        uint32_t v[4];
        for (int k = 0; k < 3; k++) {
            const uint32_t c = rnd() % 5;
            v[k] = c == 0 ? sp[rnd() % 15] : c == 1 ? (rnd() & 0xFF) : c == 2 ? (1u << (rnd() & 31)) : rnd();
        }
        v[3] = rnd() & 0xF0000000u;
        for (int k = 0; k < 4; k++) for (int b = 0; b < 4; b++) in.push_back(v[k] >> (8 * b));
    }
    FILE *f = fopen("tests/hw/mulsem/inputs.bin", "wb");
    fwrite(in.data(), 1, in.size(), f);
    fclose(f);
    f = fopen("tests/hw/mulsem/jobs.txt", "w");
    fprintf(f, "# generated by tools/hw_suite gen mulsem -- multiplier semantics (hw/arm/k_mulsem.s)\n"
               "out tests/hw/mulsem/hw\njob mulsem 2000 1\nload 0 ../build/hw/arm/k_mulsem.bin\n"
               "load 0x%X ../build/hw/arm/stub.bin\nload 0x20000 tests/hw/mulsem/inputs.bin\nword 0x20 %u\n"
               "read 0x%X 0x%X\nread 0x30000 0x%X\nrun\n", STUB, MS_N, RES, RESLEN, MS_N * 24);
    fclose(f);
    printf("wrote tests/hw/mulsem/jobs.txt and inputs.bin\n");
    return 0;
}

static int check_mulsem()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/mulsem/jobs.txt", jf) || jf.jobs.empty()) return 2;
    std::vector<uint8_t> hw, in;
    if (!read_all("tests/hw/mulsem/hw/mulsem.bin", hw) || hw.size() != RESLEN + MS_N * 24) { fprintf(stderr, "no console result\n"); return 2; }
    read_all("tests/hw/mulsem/inputs.bin", in);
    FILE *out = fopen("tests/hw/mulsem/SUMMARY.txt", "w");
    static const char *field[6] = {"MLA Rd==Rm", "MULS result", "MULS CPSR", "MLAS result", "MLAS CPSR", "MULS Rd==Rm"};
    static const char *mc[3] = {"C kept", "C = last ALU carry", "C = last shifter carry"};
    int best = 1 << 30;
    for (int c = 0; c < 3; c++) {
        ModelRun m = run_job_model(jf.jobs[0], DcWaits(), 400000000ull, nullptr, c);
        int bad[6] = {0};
        int shown = 0;
        for (unsigned i = 0; i < MS_N; i++)
            for (int k = 0; k < 6; k++) {
                const size_t o = RESLEN + i * 24 + 4 * k;
                const uint32_t mask = (k == 2 || k == 4) ? 0xF0000000u : 0xFFFFFFFFu;
                const uint32_t hv = le32(&hw[o]) & mask, mv = le32(&m.readback[o]) & mask;
                if (hv != mv) {
                    bad[k]++;
                    if (shown++ < 6)
                        fprintf(out, "  [%s] rec %u %s: Rm=%08x Rs=%08x Rn=%08x flags=%x console=%08x model=%08x\n", mc[c], i,
                                field[k], le32(&in[16 * i]), le32(&in[16 * i + 4]), le32(&in[16 * i + 8]),
                                le32(&in[16 * i + 12]) >> 28, hv, mv);
                }
            }
        char line[512];
        snprintf(line, sizeof line, "%-24s mismatches over %u records: %s %d, %s %d, %s %d, %s %d, %s %d, %s %d\n", mc[c],
                 MS_N, field[0], bad[0], field[1], bad[1], field[2], bad[2], field[3], bad[3], field[4], bad[4], field[5], bad[5]);
        fputs(line, stdout);
        fputs(line, out);
        int tot = 0;
        for (int k = 0; k < 6; k++) tot += bad[k];
        best = std::min(best, tot);
    }
    fclose(out);
    return best ? 1 : 0;
}

/* ---- blkphase: blocked half slots relative to the sample interrupt (hw/arm/k_blkphase.s) ---- */
static const unsigned BP_N1 = 256, BP_N2 = 2304;

static int gen_blkphase()
{
    if (!sh("mkdir -p tests/hw/blkphase/hw")) return 2;
    FILE *f = fopen("tests/hw/blkphase/jobs.txt", "w");
    fprintf(f, "# generated by tools/hw_suite gen blkphase -- probe P1 = sled entries skipped (N0 = 64 - P1 NOPs)\n"
               "out tests/hw/blkphase/hw\n");
    /* P1 = 31..63: N0 = 33..1 delay NOPs (the handler must end within a sample); SCILV0 = 0x80 (level 1 for bits
     * 7-10), one M write, acknowledge read of L, SCIRE 0x400.  bp = probe in the handler, bq = probe in main code. */
    for (const char *k : {"bp", "bq"})
        for (unsigned p = 31; p < 64; p++)
            for (unsigned it : {BP_N1, BP_N2})
                fprintf(f, "job %s%02u_n%u 1000 1\nload 0 ../build/hw/arm/k_blkphase%s.bin\nload 0x%X ../build/hw/arm/stub.bin\n"
                           "word 0x20 %u\nword 0x24 %u\nword 0x28 0x80\nword 0x2C 0\nword 0x30 0\nword 0x34 3\n"
                           "word 0x38 0x802D00\nword 0x3C 0x400\nread 0x%X 0x%X\nrun\n",
                        k, p, it, k[1] == 'p' ? "" : "2", STUB, it, p, RES, RESLEN);
    fclose(f);
    printf("wrote tests/hw/blkphase/jobs.txt\n");
    return 0;
}

static int check_blkphase()
{
    HwJobFile jf;
    if (!parse_jobs("tests/hw/blkphase/jobs.txt", jf)) return 2;
    auto st = read_status("tests/hw/blkphase/hw/results.txt");
    auto job = [&](const std::string &n) -> const HwJob * { for (auto &j : jf.jobs) if (j.name == n) return &j; return nullptr; };
    /* adds per sample = r7 difference / sample difference; r7 is at RES + 8 + 4*7 */
    auto r7of = [&](const std::vector<uint8_t> &b) { return le32(&b[8 + 28]); };
    std::vector<std::string> names;
    for (const char *k : {"bp", "bq"})
        for (unsigned p = 31; p < 64; p++) { char n[16]; snprintf(n, sizeof n, "%s%02u", k, p); names.push_back(n); }
    std::vector<double> hwv(names.size(), NAN);
    for (size_t i = 0; i < names.size(); i++) {
        const std::string a = names[i] + "_n" + std::to_string(BP_N1), b = names[i] + "_n" + std::to_string(BP_N2);
        std::vector<uint8_t> ha, hb;
        if (st[a] != "done" || st[b] != "done" || !read_all("tests/hw/blkphase/hw/" + a + ".bin", ha) ||
            !read_all("tests/hw/blkphase/hw/" + b + ".bin", hb) || ha.size() < RESLEN || hb.size() < RESLEN)
            continue;
        hwv[i] = (double)(r7of(hb) - r7of(ha)) / (BP_N2 - BP_N1);
    }
    /* model: sample edge at t = 0 mod 512; the blocked pair {52, 60} of dreamcast() moved by off */
    auto model_curve = [&](uint32_t off, std::vector<double> &mv) {
        DcWaits w = DcWaits::dreamcast();
        w.block_phase = (512 - off) % 512;
        for (size_t i = 0; i < names.size(); i++) {
            ModelRun ma = run_job_model(*job(names[i] + "_n" + std::to_string(BP_N1)), w),
                     mb = run_job_model(*job(names[i] + "_n" + std::to_string(BP_N2)), w);
            mv[i] = (double)(r7of(mb.readback) - r7of(ma.readback)) / (BP_N2 - BP_N1);
        }
    };
    std::vector<double> err(128);
    std::vector<std::vector<double>> curves(128, std::vector<double>(names.size()));
#pragma omp parallel for schedule(dynamic)
    for (int o = 0; o < 128; o++) {
        model_curve(4 * o, curves[o]);
        double e = 0;
        for (size_t i = 0; i < names.size(); i++)
            if (!std::isnan(hwv[i])) e += (curves[o][i] - hwv[i]) * (curves[o][i] - hwv[i]);
        err[o] = e;
    }
    std::vector<int> ord(128);
    for (int i = 0; i < 128; i++) ord[i] = i;
    std::sort(ord.begin(), ord.end(), [&](int a, int b) { return err[a] < err[b]; });
    const int best = ord[0];
    FILE *out = fopen("tests/hw/blkphase/SUMMARY.txt", "w");
    auto both = [&](const char *fmt, auto... a) { printf(fmt, a...); fprintf(out, fmt, a...); };
    both("%s", "adds per sample; bp = probe in the FIQ handler after N0 = 64 - P1 NOPs, bq = probe in main code after a "
               "handler of that length.  Model: sample edge at 0, blocked pair at +x/+x+8 MCLK:\n");
    for (int i = 0; i < 6; i++)
        both("  blocked at +%3u/+%3u: err %.4f\n", (52 + 4 * ord[i]) % 512, (60 + 4 * ord[i]) % 512, err[ord[i]]);
    for (size_t i = 0; i < names.size(); i++)
        both("  %s  console %8.4f  model %8.4f\n", names[i].c_str(), hwv[i], curves[best][i]);
    fclose(out);
    return 0;
}

/* ---- dspport (DSP TEMP writes vs CPU TEMP reads) and blkshot (single-shot probes): console vs model ---- */
static int check_counts(const char *suite, const std::vector<std::pair<std::string, std::string>> &pairs, double div,
                        const std::vector<std::string> &singles)
{
    HwJobFile jf;
    if (!parse_jobs(std::string("tests/hw/") + suite + "/jobs.txt", jf)) return 2;
    auto job = [&](const std::string &n) -> const HwJob * { for (auto &j : jf.jobs) if (j.name == n) return &j; return nullptr; };
    auto hw7 = [&](const std::string &n) { std::vector<uint8_t> b; read_all(std::string("tests/hw/") + suite + "/hw/" + n + ".bin", b);
                                           return b.size() >= 40 ? le32(&b[36]) : 0xFFFFFFFFu; };
    auto m7 = [&](const std::string &n) { ModelRun r = run_job_model(*job(n), DcWaits::dreamcast()); return le32(&r.readback[36]); };
    FILE *out = fopen((std::string("tests/hw/") + suite + "/SUMMARY.txt").c_str(), "w");
    int bad = 0, n = 0;
    std::vector<std::string> lines(pairs.size() + singles.size());
    std::vector<int> badv(lines.size());
#pragma omp parallel for schedule(dynamic)
    for (size_t i = 0; i < lines.size(); i++) {
        char l[160];
        if (i < pairs.size()) {
            const double h = ((double)hw7(pairs[i].second) - hw7(pairs[i].first)) / div,
                         m = ((double)m7(pairs[i].second) - m7(pairs[i].first)) / div;
            badv[i] = fabs(h - m) > 0.5;
            snprintf(l, sizeof l, "%-24s console %7.3f model %7.3f%s\n", pairs[i].first.c_str(), h, m, badv[i] ? "  DIFFERENT" : "");
        } else {
            const std::string &s1 = singles[i - pairs.size()];
            std::map<uint32_t, int> votes;
            for (char r : {'a', 'b', 'c'}) votes[hw7(s1 + r)]++;
            uint32_t hv = 0; int c = 0;
            for (auto &v : votes) if (v.second > c) { c = v.second; hv = v.first; }
            const uint32_t mv = m7(s1 + "a");
            badv[i] = hv != mv;
            snprintf(l, sizeof l, "%-24s console %4u (%d/3 runs) model %4u%s\n", s1.c_str(), hv, c, mv, badv[i] ? "  DIFFERENT" : "");
        }
        lines[i] = l;
    }
    for (size_t i = 0; i < lines.size(); i++) { fputs(lines[i].c_str(), out); bad += badv[i]; n++; }
    char l[128];
    snprintf(l, sizeof l, "%d/%d points: console = model (DcWaits::dreamcast; DcArmBus DSP step and slot defaults)\n", n - bad, n);
    fputs(l, out);
    fputs(l, stdout);
    fclose(out);
    return bad ? 1 : 0;
}

/* dspmem / dspmem1: SH4-timed kernels (ITER 64 / 576) while the DSP accesses wave RAM; console U per iteration
 * (U from the no-DSP nop kernel of tests/hw/timing: 8.8352 SH4 cycles) against the model's MCLK per iteration */
static int check_timed(const char *suite, double tol)
{
    HwJobFile jf;
    if (!parse_jobs(std::string("tests/hw/") + suite + "/jobs.txt", jf)) return 2;
    std::map<std::string, double> hw;
    {
        FILE *f = fopen((std::string("tests/hw/") + suite + "/hw/results.txt").c_str(), "r");
        if (!f) return 2;
        char line[512];
        while (fgets(line, sizeof line, f)) {
            char n[128], st[32];
            if (sscanf(line, "%127s %31s", n, st) != 2 || strcmp(st, "done")) continue;
            std::vector<double> v;
            char *p = line;
            for (int i = 0; i < 3; i++) { p = strchr(p, ' '); if (p) p++; }
            while (p && *p) { char *e; double x = strtod(p, &e); if (e == p) break; v.push_back(x); p = e; }
            std::sort(v.begin(), v.end());
            if (!v.empty()) hw[n] = v[v.size() / 2];
        }
        fclose(f);
    }
    const double U = 8.8352;
    std::vector<std::string> bases;
    for (auto &j : jf.jobs)
        if (j.name.size() > 4 && j.name.compare(j.name.size() - 4, 4, "_n64") == 0) bases.push_back(j.name.substr(0, j.name.size() - 4));
    std::vector<std::string> lines(bases.size());
    std::vector<int> badv(bases.size());
#pragma omp parallel for schedule(dynamic)
    for (size_t i = 0; i < bases.size(); i++) {
        const HwJob *a = nullptr, *b = nullptr;
        for (auto &j : jf.jobs) { if (j.name == bases[i] + "_n64") a = &j; if (j.name == bases[i] + "_n576") b = &j; }
        const double h = (hw[bases[i] + "_n576"] - hw[bases[i] + "_n64"]) / 512 / U;
        /* asynchronous SH4 traffic: average over 8 starting phases of its stream */
        const int np = a->sh4mode == 1 || a->sh4mode == 2 ? 8 : 1;
        double m = 0;
        for (int ph = 0; ph < np; ph++) {
            ModelRun ma = run_job_model(*a, DcWaits::dreamcast(), 400000000ull, nullptr, -1, (double)ph / np),
                     mb = run_job_model(*b, DcWaits::dreamcast(), 400000000ull, nullptr, -1, (double)ph / np);
            m += (double)(mb.cycles - ma.cycles) / 512 / np;
        }
        badv[i] = fabs(h - m) > tol;
        char l[160];
        snprintf(l, sizeof l, "%-20s console %8.2f model %8.2f%s\n", bases[i].c_str(), h, m, badv[i] ? "  DIFFERENT" : "");
        lines[i] = l;
    }
    FILE *out = fopen((std::string("tests/hw/") + suite + "/SUMMARY.txt").c_str(), "w");
    int bad = 0;
    for (size_t i = 0; i < lines.size(); i++) { fputs(lines[i].c_str(), out); bad += badv[i]; }
    char l[160];
    snprintf(l, sizeof l, "%zu/%zu kernels within %.2f MCLK per iteration (DcWaits::dreamcast)\n", lines.size() - bad, lines.size(), tol);
    fputs(l, out);
    fputs(l, stdout);
    fclose(out);
    return bad ? 1 : 0;
}

static int check_dspport()
{
    std::vector<std::pair<std::string, std::string>> pairs;
    for (const char *pr : {"none", "w00", "w32", "w64", "w96"})
        for (const char *k : {"dp", "dq"})
            for (int p = 31; p < 64; p++) {
                const std::string b = std::string(pr) + "_" + k + std::to_string(p);
                pairs.push_back({b + "_n128", b + "_n1152"});
            }
    return check_counts("dspport", pairs, 1024, {});
}

static int check_blkshot()
{
    std::vector<std::string> singles;
    for (const char *k : {"bs", "bt"})
        for (int p = 31; p < 64; p++) singles.push_back(std::string(k) + std::to_string(p));
    return check_counts("blkshot", {}, 1, singles);
}

/* tests/hw/collide2 (functional, the ARM in reset during the readout; see its gen.py): who wins a slot shared by a
 * channel fetch and a DSP access.  Expected: the channel's fetch goes on (MIXS0 follows its ramp), a DSP write in
 * its slot is dropped, a DSP read in its slot returns the channel's word. */
static int check_collide2(const std::string &dir = "tests/hw/collide2/hw")
{
    /* dir: the console's readouts, or another AICA's (caique rtl/v1 armjob_tb -w DIR); SUMMARY.txt only for the console */
    const bool console = dir == "tests/hw/collide2/hw";
    FILE *out = fopen(console ? "tests/hw/collide2/SUMMARY.txt" : (dir + "/SUMMARY.txt").c_str(), "w");
    int bad = 0, total = 0;
    for (int K : {10, 20, 30, 40})
        for (const char *c : {"none", "ch", "rd", "ch_rd", "ch_rd2", "wr", "ch_wr", "ch_wr2"}) {
            const std::string n = "k" + std::to_string(K) + "_" + c;
            uint32_t v[35] = {0};
            FILE *f = fopen((dir + "/" + n + ".bin").c_str(), "rb");
            const bool have = f && fread(v, 4, 35, f) == 35;
            if (f) fclose(f);
            const std::string cs = c;
            const bool chan = cs.compare(0, 2, "ch") == 0;
            const uint32_t word32 = v[0] & 0xFFFF, mems0 = ((v[2] & 0xFFFF) << 8) | (v[1] & 0xFF);
            uint32_t want_mems = 0x7E7E00, want_word = 0x5555;   /* marker / prefill: nothing written */
            if (cs == "rd" || cs == "ch_rd2") want_mems = 0x123400;   /* the DSP's own word */
            if (cs == "wr" || cs == "ch_wr2") want_word = 0x1E1E;
            const bool mems_ok = cs == "ch_rd" ? (mems0 >> 16) == 0xA0 && (mems0 & 0xFF) == 0 : mems0 == want_mems;
            bool mixs_ok = true;   /* MIXS0, 16 reads ~1 sample apart: the ramp (+0..2 per read, one loop wrap) or silence */
            int wraps = 0;
            for (int i = 0; i < 16; i++) {
                const int32_t x = (int32_t)(((((v[19 + i] & 0xFFFF) << 4) | (v[3 + i] & 0xF)) << 12)) >> 12;
                if (!chan) { mixs_ok &= x == 0; continue; }
                mixs_ok &= (x >> 4 & 0xFFFF) >= 0xA000 && (x >> 4 & 0xFFFF) < 0xA200;
                if (i) {
                    const int32_t p = (int32_t)(((((v[18 + i] & 0xFFFF) << 4) | (v[2 + i] & 0xF)) << 12)) >> 12;
                    const int d = ((x - p) >> 4);
                    if (d < 0) wraps++;
                    else mixs_ok &= d <= 2;
                }
            }
            mixs_ok &= wraps <= 1;
            const bool ok = have && mems_ok && word32 == want_word && mixs_ok;
            total++;
            bad += !ok;
            char l[200];
            snprintf(l, sizeof l, "%-10s MEMS0 %06x  word32 %04x  MIXS0 %s%s\n", n.c_str(), mems0, word32,
                     chan ? "ramp" : "silent", ok ? "" : "  DIFFERENT");
            fputs(l, out);
        }
    char l[160];
    snprintf(l, sizeof l, "%d/%d cases as expected (channel keeps the slot: DSP write dropped, DSP read gets the channel's word)\n",
             total - bad, total);
    fputs(l, out);
    fputs(l, stdout);
    fclose(out);
    return bad ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "collide2")) return check_collide2();
    if (argc == 4 && !strcmp(argv[1], "check") && !strcmp(argv[2], "collide2")) return check_collide2(argv[3]);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "dspport")) return check_dspport();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "dspmem")) return check_timed("dspmem", 0.1);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "dspmem1")) return check_timed("dspmem1", 0.1);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "dspmem1r")) return check_timed("dspmem1r", 0.1);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "sgc")) return check_timed("sgc", 0.1);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "collide")) return check_timed("collide", 0.1);
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "sgcadp")) return check_timed("sgcadp", 0.1);
    if (argc == 4 && !strcmp(argv[1], "check") && !strcmp(argv[2], "sh4load")) return check_timed("sh4load", atof(argv[3]));
    if (argc == 4 && !strcmp(argv[1], "check") && !strcmp(argv[2], "combo")) return check_timed("combo", atof(argv[3]));
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "blkshot")) return check_blkshot();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "blkphase")) return gen_blkphase();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "blkphase")) return check_blkphase();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "mulsem")) return gen_mulsem();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "mulsem")) return check_mulsem();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "vendor")) return gen_vendor();
    if (argc == 3 && !strcmp(argv[1], "gen") && !strcmp(argv[2], "qemu_diff")) return gen_qemu_diff();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "vendor")) return check_vendor();
    if (argc == 3 && !strcmp(argv[1], "check") && !strcmp(argv[2], "qemu_diff")) return check_qemu_diff();
    fprintf(stderr, "usage: hw_suite gen|check vendor|qemu_diff|mulsem   (from wren7-rtl/model)\n");
    return 2;
}
