@ generated by tools/hw_timing -- kernel addpc: data op to PC (skips one), 8 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0
    b loop
    .ltorg
    .balign 64
loop:
    .rept 8
    add pc, pc, #0
    mov r0, r0
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
