@ generated by tools/hw_timing -- kernel mix14: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x32da9164
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    ldr r0, [r7, #8]
    add r0, r0, #117
    stmia r3, {r6, r8-r11}
    b 1f
    1:
    ldr r0, [r4]
    mul r10, r1, r13
    mul r10, r1, r13
    b 1f
    1:
    eors r6, r6, r8, ror #31
    strb r0, [r7, #176]
    swp r11, r11, [r7]
    addeq r0, r0, #1
    ldr r0, [r4]
    mul r10, r1, r13
    eors r6, r6, r8, ror #29
    swpb r11, r11, [r3]
    str r0, [r7, #168]
    str r0, [r5]
    ldr r0, [r4]
    b 1f
    1:
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    mov r0, r0
    movs r8, r8, lsr r2
    eors r6, r6, r8, ror #17
    mov r0, r0
    ldr r0, [r4]
    swp r11, r11, [r3]
    strb r0, [r3, #44]
    swpb r11, r11, [r3]
    ldr r0, [r4]
    add r9, r9, r1, lsl r2
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
