@ generated by tools/hw_timing -- kernel mix13: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x00000001
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    add r9, r9, r1, lsl r2
    add r0, r0, #14
    stmia r7, {r6, r8}
    mla r10, r1, r13, r9
    add r9, r9, r1, lsl r2
    ldr r0, [r7, #40]
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    str r0, [r5]
    str r0, [r5]
    mla r10, r1, r13, r9
    mul r10, r1, r13
    str r0, [r7, #52]
    add r9, r9, r1, lsl r2
    eors r6, r6, r8, ror #15
    eors r6, r6, r8, ror #26
    add r0, r0, #250
    stmia r7, {r6, r8}
    ldrb r0, [r7, #16]
    mov r0, r0
    mul r10, r1, r13
    ldr r0, [r4]
    movs r8, r8, lsr r2
    ldr r0, [r3, #88]
    addeq r0, r0, #1
    add r9, r9, r1, lsl r2
    add r9, r9, r1, lsl r2
    ldmia r7, {r6, r8-r11}
    addeq r0, r0, #1
    mul r10, r1, r13
    ldr r0, [r4]
    swpb r11, r11, [r7]
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
