@ generated by tools/hw_timing -- kernel mix1: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x028ab385
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    ldr r0, [r4]
    addeq r0, r0, #1
    mul r10, r1, r13
    mul r10, r1, r13
    ldrb r0, [r7, #236]
    ldr r0, [r4]
    add r0, r0, #145
    strb r0, [r7, #76]
    eors r6, r6, r8, ror #21
    ldrb r0, [r3, #4]
    stmia r7, {r6}
    mla r10, r1, r13, r9
    strb r0, [r7, #240]
    mla r10, r1, r13, r9
    addeq r0, r0, #1
    mov r0, r0
    str r0, [r7, #172]
    mul r10, r1, r13
    addeq r0, r0, #1
    addeq r0, r0, #1
    mul r10, r1, r13
    ldmia r7, {r6}
    ldmia r7, {r6, r8-r10}
    movs r8, r8, lsr r2
    ldr r0, [r3, #36]
    mla r10, r1, r13, r9
    b 1f
    1:
    mul r10, r1, r13
    ldr r0, [r4]
    swpb r11, r11, [r7]
    eors r6, r6, r8, ror #11
    ldr r0, [r4]
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
