@ generated by tools/hw_timing -- kernel mix15: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x000000df
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    ldr r0, [r3, #160]
    mov r0, r0
    ldr r0, [r3, #248]
    add r9, r9, r1, lsl r2
    add r0, r0, #177
    mov r0, r0
    stmia r3, {r0, r6, r8-r11, r14}
    ldr r0, [r4]
    mov r0, r0
    add r0, r0, #47
    b 1f
    1:
    mla r10, r1, r13, r9
    eors r6, r6, r8, ror #4
    add r9, r9, r1, lsl r2
    movs r8, r8, lsr r2
    b 1f
    1:
    swp r11, r11, [r3]
    str r0, [r5]
    str r0, [r5]
    add r0, r0, #11
    strb r0, [r7, #148]
    addeq r0, r0, #1
    addeq r0, r0, #1
    ldmia r7, {r6, r8-r11}
    b 1f
    1:
    eors r6, r6, r8, ror #27
    mla r10, r1, r13, r9
    mov r0, r0
    add r9, r9, r1, lsl r2
    mla r10, r1, r13, r9
    addeq r0, r0, #1
    str r0, [r5]
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
