@ generated by tools/hw_timing -- kernel mix12: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x449a8ee7
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    str r0, [r5]
    str r0, [r3, #104]
    stmia r3, {r0, r6, r8-r11, r14}
    movs r8, r8, lsr r2
    movs r8, r8, lsr r2
    add r0, r0, #156
    ldrb r0, [r7, #188]
    str r0, [r5]
    stmia r3, {r6, r8-r11}
    mov r0, r0
    add r0, r0, #76
    add r0, r0, #14
    add r9, r9, r1, lsl r2
    str r0, [r7, #80]
    str r0, [r5]
    eors r6, r6, r8, ror #13
    eors r6, r6, r8, ror #6
    mov r0, r0
    add r0, r0, #95
    mul r10, r1, r13
    ldmia r7, {r6, r8-r11}
    addeq r0, r0, #1
    eors r6, r6, r8, ror #19
    str r0, [r3, #140]
    stmia r3, {r6, r8}
    swp r11, r11, [r3]
    ldr r0, [r3, #84]
    mov r0, r0
    swpb r11, r11, [r7]
    str r0, [r7, #252]
    ldrb r0, [r7, #44]
    strb r0, [r7, #252]
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
