@ generated by tools/hw_timing -- kernel mix11: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x00000000
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    addeq r0, r0, #1
    mov r0, r0
    movs r8, r8, lsr r2
    add r0, r0, #24
    mul r10, r1, r13
    mla r10, r1, r13, r9
    eors r6, r6, r8, ror #14
    b 1f
    1:
    add r0, r0, #205
    ldr r0, [r4]
    strb r0, [r7, #84]
    str r0, [r7, #4]
    b 1f
    1:
    ldrb r0, [r3, #192]
    ldr r0, [r4]
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    mul r10, r1, r13
    str r0, [r5]
    stmia r7, {r0, r6, r8-r11, r14}
    b 1f
    1:
    eors r6, r6, r8, ror #21
    ldrb r0, [r3, #220]
    eors r6, r6, r8, ror #21
    ldr r0, [r4]
    add r9, r9, r1, lsl r2
    ldmia r3, {r0, r6, r8-r11, r14}
    mla r10, r1, r13, r9
    swp r11, r11, [r7]
    add r9, r9, r1, lsl r2
    add r0, r0, #214
    mla r10, r1, r13, r9
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
