@ generated by tools/hw_timing -- kernel mix10: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x0b2f93f6
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    stmia r3, {r6, r8}
    add r0, r0, #118
    b 1f
    1:
    b 1f
    1:
    ldmia r3, {r6, r8-r11}
    mla r10, r1, r13, r9
    ldr r0, [r3, #12]
    ldr r0, [r4]
    mov r0, r0
    ldrb r0, [r3, #184]
    add r9, r9, r1, lsl r2
    ldrb r0, [r7, #140]
    mul r10, r1, r13
    eors r6, r6, r8, ror #4
    add r9, r9, r1, lsl r2
    str r0, [r5]
    strb r0, [r7, #188]
    strb r0, [r7, #120]
    ldr r0, [r4]
    mla r10, r1, r13, r9
    eors r6, r6, r8, ror #9
    addeq r0, r0, #1
    add r9, r9, r1, lsl r2
    movs r8, r8, lsr r2
    movs r8, r8, lsr r2
    str r0, [r5]
    mul r10, r1, r13
    ldrb r0, [r7, #56]
    strb r0, [r3, #28]
    b 1f
    1:
    mov r0, r0
    movs r8, r8, lsr r2
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
