@ generated by tools/hw_timing -- kernel mix2: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x013a8ac5
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    eors r6, r6, r8, ror #4
    mul r10, r1, r13
    str r0, [r3, #216]
    b 1f
    1:
    addeq r0, r0, #1
    mla r10, r1, r13, r9
    str r0, [r5]
    add r0, r0, #210
    ldmia r3, {r6, r8}
    eors r6, r6, r8, ror #12
    add r0, r0, #40
    mov r0, r0
    eors r6, r6, r8, ror #30
    b 1f
    1:
    ldr r0, [r4]
    stmia r3, {r6}
    ldrb r0, [r7, #36]
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    eors r6, r6, r8, ror #17
    ldr r0, [r7, #80]
    addeq r0, r0, #1
    ldr r0, [r4]
    str r0, [r5]
    movs r8, r8, lsr r2
    stmia r7, {r6, r8-r10}
    swpb r11, r11, [r3]
    str r0, [r5]
    eors r6, r6, r8, ror #1
    mul r10, r1, r13
    strb r0, [r7, #120]
    b 1f
    1:
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
