@ generated by tools/hw_timing -- kernel mix3: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x0000000c
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    add r9, r9, r1, lsl r2
    b 1f
    1:
    str r0, [r3, #212]
    str r0, [r5]
    mul r10, r1, r13
    strb r0, [r7, #24]
    b 1f
    1:
    stmia r3, {r6, r8-r10}
    eors r6, r6, r8, ror #8
    eors r6, r6, r8, ror #9
    stmia r3, {r6, r8-r10}
    ldrb r0, [r7, #128]
    movs r8, r8, lsr r2
    str r0, [r5]
    stmia r7, {r0, r6, r8-r11, r14}
    b 1f
    1:
    movs r8, r8, lsr r2
    stmia r3, {r6, r8-r11}
    eors r6, r6, r8, ror #19
    str r0, [r5]
    str r0, [r5]
    movs r8, r8, lsr r2
    stmia r7, {r6, r8-r10}
    mla r10, r1, r13, r9
    mov r0, r0
    swp r11, r11, [r3]
    movs r8, r8, lsr r2
    str r0, [r5]
    add r0, r0, #57
    strb r0, [r3, #184]
    strb r0, [r3, #144]
    swpb r11, r11, [r7]
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
