@ generated by tools/hw_timing -- kernel mix4: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x00005e75
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    stmia r7, {r0, r6, r8-r11, r14}
    strb r0, [r7, #184]
    ldr r0, [r4]
    stmia r7, {r6, r8-r11}
    ldmia r7, {r6, r8-r10}
    addeq r0, r0, #1
    ldmia r7, {r6}
    str r0, [r5]
    str r0, [r3, #0]
    ldmia r7, {r6, r8-r10}
    addeq r0, r0, #1
    ldmia r7, {r6, r8}
    mov r0, r0
    eors r6, r6, r8, ror #8
    eors r6, r6, r8, ror #3
    add r0, r0, #52
    str r0, [r5]
    movs r8, r8, lsr r2
    b 1f
    1:
    eors r6, r6, r8, ror #15
    ldr r0, [r4]
    swpb r11, r11, [r3]
    mla r10, r1, r13, r9
    mla r10, r1, r13, r9
    add r0, r0, #158
    add r0, r0, #224
    mla r10, r1, r13, r9
    str r0, [r5]
    ldmia r3, {r6, r8-r11}
    mov r0, r0
    b 1f
    1:
    eors r6, r6, r8, ror #29
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
