@ generated by tools/hw_timing -- kernel mix5: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x00000045
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    mla r10, r1, r13, r9
    ldr r0, [r4]
    eors r6, r6, r8, ror #3
    stmia r7, {r6, r8-r11}
    ldmia r3, {r0, r6, r8-r11, r14}
    mul r10, r1, r13
    str r0, [r3, #116]
    addeq r0, r0, #1
    ldr r0, [r4]
    movs r8, r8, lsr r2
    strb r0, [r7, #92]
    ldr r0, [r4]
    ldmia r3, {r6, r8-r11}
    str r0, [r5]
    b 1f
    1:
    add r9, r9, r1, lsl r2
    eors r6, r6, r8, ror #6
    ldmia r3, {r6, r8-r10}
    add r9, r9, r1, lsl r2
    swpb r11, r11, [r7]
    str r0, [r5]
    add r0, r0, #238
    b 1f
    1:
    stmia r7, {r6, r8-r11}
    eors r6, r6, r8, ror #3
    movs r8, r8, lsr r2
    add r0, r0, #69
    ldmia r3, {r6, r8}
    mov r0, r0
    eors r6, r6, r8, ror #21
    str r0, [r5]
    add r0, r0, #172
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
