@ generated by tools/hw_timing -- kernel mix6: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x00000534
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    str r0, [r5]
    ldrb r0, [r3, #240]
    b 1f
    1:
    mla r10, r1, r13, r9
    stmia r3, {r0, r6, r8-r11, r14}
    add r9, r9, r1, lsl r2
    str r0, [r5]
    strb r0, [r7, #220]
    swp r11, r11, [r7]
    str r0, [r7, #96]
    movs r8, r8, lsr r2
    strb r0, [r3, #124]
    ldr r0, [r4]
    str r0, [r7, #100]
    stmia r3, {r6, r8-r10}
    ldmia r7, {r0, r6, r8-r11, r14}
    ldrb r0, [r3, #128]
    ldr r0, [r4]
    swp r11, r11, [r3]
    addeq r0, r0, #1
    eors r6, r6, r8, ror #25
    ldr r0, [r4]
    mov r0, r0
    ldr r0, [r4]
    mul r10, r1, r13
    add r0, r0, #157
    b 1f
    1:
    str r0, [r5]
    swpb r11, r11, [r7]
    b 1f
    1:
    ldr r0, [r4]
    ldmia r3, {r6, r8-r10}
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
