@ generated by tools/hw_timing -- kernel mix7: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x2848325f
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    str r0, [r5]
    movs r8, r8, lsr r2
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    mov r0, r0
    movs r8, r8, lsr r2
    ldrb r0, [r3, #68]
    ldmia r7, {r0, r6, r8-r11, r14}
    mul r10, r1, r13
    add r9, r9, r1, lsl r2
    add r9, r9, r1, lsl r2
    mul r10, r1, r13
    strb r0, [r3, #188]
    ldmia r3, {r6}
    add r9, r9, r1, lsl r2
    add r9, r9, r1, lsl r2
    b 1f
    1:
    str r0, [r3, #96]
    str r0, [r5]
    ldmia r3, {r6, r8-r10}
    ldr r0, [r3, #172]
    add r0, r0, #132
    mov r0, r0
    addeq r0, r0, #1
    add r9, r9, r1, lsl r2
    add r9, r9, r1, lsl r2
    addeq r0, r0, #1
    add r0, r0, #18
    addeq r0, r0, #1
    movs r8, r8, lsr r2
    mul r10, r1, r13
    b 1f
    1:
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
