@ generated by tools/hw_timing -- kernel mix8: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x05089665
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    mla r10, r1, r13, r9
    b 1f
    1:
    stmia r7, {r6, r8-r10}
    mul r10, r1, r13
    ldmia r3, {r6}
    add r0, r0, #76
    eors r6, r6, r8, ror #7
    add r0, r0, #8
    eors r6, r6, r8, ror #10
    b 1f
    1:
    mov r0, r0
    ldrb r0, [r7, #80]
    addeq r0, r0, #1
    addeq r0, r0, #1
    add r9, r9, r1, lsl r2
    ldr r0, [r4]
    str r0, [r5]
    mov r0, r0
    ldr r0, [r7, #116]
    stmia r7, {r6}
    ldr r0, [r4]
    add r9, r9, r1, lsl r2
    eors r6, r6, r8, ror #25
    swp r11, r11, [r3]
    movs r8, r8, lsr r2
    str r0, [r5]
    addeq r0, r0, #1
    ldrb r0, [r3, #32]
    addeq r0, r0, #1
    ldr r0, [r3, #200]
    swpb r11, r11, [r3]
    stmia r3, {r6, r8-r10}
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
