@ generated by tools/hw_timing -- kernel mix9: random mix, 1 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0x000037a6
    b loop
    .ltorg
    .balign 64
loop:
    .rept 1
    add r0, r0, #255
    str r0, [r5]
    mla r10, r1, r13, r9
    stmia r7, {r6}
    movs r8, r8, lsr r2
    add r9, r9, r1, lsl r2
    swp r11, r11, [r7]
    add r9, r9, r1, lsl r2
    eors r6, r6, r8, ror #16
    ldmia r7, {r6}
    ldr r0, [r3, #20]
    strb r0, [r3, #192]
    b 1f
    1:
    mul r10, r1, r13
    swpb r11, r11, [r3]
    ldr r0, [r4]
    stmia r3, {r6}
    eors r6, r6, r8, ror #5
    ldr r0, [r4]
    swp r11, r11, [r3]
    str r0, [r5]
    mla r10, r1, r13, r9
    swp r11, r11, [r3]
    ldr r0, [r4]
    str r0, [r5]
    mul r10, r1, r13
    swpb r11, r11, [r3]
    b 1f
    1:
    swpb r11, r11, [r7]
    mov r0, r0
    ldr r0, [r4]
    eors r6, r6, r8, ror #5
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
