@ generated by tools/hw_timing -- kernel und: undefined trap + movs pc, lr, 8 per iteration
    .include "crt.inc"
_start:
    ldr r12, ITER
    ldr r1, =0x12345679
    ldr r2, P1
    ldr r3, =0x100000
    ldr r4, =0x802800
    ldr r5, =0x803000
    ldr r7, =0x180000
    ldr r13, =0
    ldr r0, =0xE1B0F00E
    mov r6, #4
    str r0, [r6]
    b loop
    .ltorg
    .balign 64
loop:
    .rept 8
    .word 0xE7F000F0
    .endr
    subs r12, r12, #1
    bne loop
    b STUB
