# collide2: channel fetch vs DSP access on the same slot, read back with the ARM held in reset (no ARM reads to
# overwrite the memory read latch).  k_dspmem_nop with ITER 1 only loads MPRO / RBP / MADRS[0] = 0 and stops; the
# channel and the DSP then run alone, the SH4 reads MEMS0 and MIXS0 (rreg) after 5 ms.
#   rd: MRD at step s (TABLE, MASA 0 -> word 0 of RBP = 0x1234), NOFL at s+1, IWT at s+3 -> MEMS0 (marker 0x7E7E00)
#   wr: step s-1 ACC = MEMS5 (0x3C3C00) * COEF 0.5 = 0x1E1E00; MWT at s (NOFL, MASA 1 -> word 32, prefilled 0x5555)
#   channel K at step 2K-14 plays a looped ramp 0xA000 + i (PCM16, 256 words), IMXL 15 -> MIXS0, TL 0
import struct
TABLE, MWT, MRD, NOFL = 1 << 15, 1 << 14, 1 << 13, 1 << 15
def prog(rd=None, wr=None):
    img = bytearray(2048)
    def w(step, k, v):
        o = 16 * (step % 128) + 4 * k
        struct.pack_into('<I', img, o, struct.unpack_from('<I', img, o)[0] | v)
    if rd is not None:
        w(rd, 2, TABLE | MRD); w(rd, 3, NOFL); w(rd + 1, 3, NOFL); w(rd + 2, 3, NOFL); w(rd + 3, 1, 1 << 6)
    if wr is not None:
        w(wr - 1, 1, (1 << 15) | (1 << 13) | (5 << 7)); w(wr - 1, 2, 1 << 1)   # X = INPUTS(MEMS5), Y = COEF, B = 0
        w(wr, 2, TABLE | MWT); w(wr, 3, NOFL | (1 << 9))
    return img
def chan(c, sa=0x180000):
    b = 0x80 * c
    w = [(b + 0x04, sa & 0xFFFF), (b + 0x08, 0), (b + 0x0C, 0x100), (b + 0x10, 0x001F), (b + 0x14, 0x3C1F),
         (b + 0x18, 0), (b + 0x1C, 0), (b + 0x20, 0x00F0), (b + 0x24, 0), (b + 0x28, 0x0020)]
    w += [(b + 0x2C + 4 * i, 0x1FF8) for i in range(5)] + [(b + 0x40, 0x1F1F), (b + 0x44, 0x1F1F)]
    w += [(b + 0x00, 0x4000 | (1 << 9) | ((sa >> 16) & 0x7F))]
    w.append((b + 0x00, w[-1][1] | 0x8000))
    return w
tgt = bytearray(0x100); struct.pack_into('<H', tgt, 0x00, 0x1234); struct.pack_into('<H', tgt, 0x40, 0x5555)
open('tests/hw/collide2/dsp_data.bin', 'wb').write(tgt)
lines = ['# generated by gen.py (see there)', 'out tests/hw/collide2/hw']
for K in (10, 20, 30, 40):
    s = 2 * K - 14
    for n, (chs, rd, wr) in {'none': ([], None, None), 'ch': ([K], None, None), 'rd': ([], s, None),
                              'ch_rd': ([K], s, None), 'ch_rd2': ([K], s + 2, None), 'wr': ([], None, s),
                              'ch_wr': ([K], None, s), 'ch_wr2': ([K], None, s + 2)}.items():
        name = f'k{K}_{n}'
        open(f'tests/hw/collide2/mpro_{name}.bin', 'wb').write(prog(rd, wr))
        regs = [(0x3204, 32), (0x4404, 0x7E7E), (0x442C, 0x3C3C)]
        if wr is not None: regs.append((0x3000 + 4 * (wr - 1), 0x0800 << 3))
        for c in chs: regs += chan(c)
        lines += [f'job {name} 2000 1', 'load 0 ../build/hw/arm/k_dspmem_nop.bin', 'load 0x1FE000 ../build/hw/arm/stub.bin',
                  f'load 0x20000 tests/hw/collide2/mpro_{name}.bin', 'load 0x180000 tests/hw/collide2/chan_ramp.bin',
                  'load 0x1C0000 tests/hw/collide2/dsp_data.bin', 'word 0x20 1', 'quiet']
        lines += [f'areg 0x{a:04X} 0x{v:04X}' for (a, v) in regs]
        lines += ['read 0x1C0040 4', 'rreg 0x4400 1', 'rreg 0x4404 1', 'rreg 0x4500 16', 'rreg 0x4504 16', 'run']
open('tests/hw/collide2/jobs.txt', 'w').write('\n'.join(lines) + '\n')
