# collide: channel fetch vs DSP access on the same slot, ARM timing (k_dspmem_* kernels, ITER 64 / 576).
# Channel K sits at step s = 2K-14; cases: ch (channel alone), rd / wr (DSP alone at s), ch_rd / ch_wr (both at s),
# ch_rd2 / ch_wr2 (DSP at s+2).  rd: MRD at s (TABLE, MASA 0 -> word 0 of RBP = 0x1234), NOFL s+1..s+2, IWT at s+3
# -> MEMS0; wr: MWT at s (MASA 1 -> word 32, prefilled 0x5555; ACC is not set up, so the value is arbitrary).
# The kernels' epilogue saves MEMS0 at 0x1FF100; with the ARM running, its reads can replace an even-step MRD's
# result (see NOTES.md), so the clean functional readout is tests/hw/collide2.  K 61-63 = steps 108/110/112, around
# the fixed pair at 109/111.   Run from wren7-rtl/model: python3 tests/hw/collide/gen.py
import struct
TABLE, MWT, MRD, NOFL = 1 << 15, 1 << 14, 1 << 13, 1 << 15
def prog(rd=None, wr=None):
    img = bytearray(2048)
    def w(step, k, v):
        o = 16 * (step % 128) + 4 * k
        struct.pack_into('<I', img, o, struct.unpack_from('<I', img, o)[0] | v)
    if rd is not None:
        w(rd, 2, TABLE | MRD); w(rd, 3, NOFL); w(rd + 1, 3, NOFL); w(rd + 2, 3, NOFL); w(rd + 3, 1, 1 << 6)
    if wr is not None:
        w(wr, 2, TABLE | MWT); w(wr, 3, NOFL | (1 << 9))
    return img
def chan(c, sa=0x180000):
    b = 0x80 * c
    w = [(b + 0x04, sa & 0xFFFF), (b + 0x08, 0), (b + 0x0C, 0x100), (b + 0x10, 0x001F), (b + 0x14, 0x3C1F),
         (b + 0x18, 0), (b + 0x1C, 0), (b + 0x20, 0), (b + 0x24, 0), (b + 0x28, 0xFF20)]
    w += [(b + 0x2C + 4 * i, 0x1FF8) for i in range(5)] + [(b + 0x40, 0x1F1F), (b + 0x44, 0x1F1F)]
    w += [(b + 0x00, 0x4000 | (1 << 9) | ((sa >> 16) & 0x7F))]
    w.append((b + 0x00, w[-1][1] | 0x8000))
    return w
tgt = bytearray(0x100); struct.pack_into('<H', tgt, 0x00, 0x1234); struct.pack_into('<H', tgt, 0x40, 0x5555)
open('tests/hw/collide/dsp_data.bin', 'wb').write(tgt)
open('tests/hw/collide/chan_ramp.bin', 'wb').write(b''.join(struct.pack('<H', 0xA000 + i) for i in range(512)))
lines = ['# generated by gen.py (see there)', 'out tests/hw/collide/hw']
for K in (10, 20, 30, 40, 61, 62, 63):
    s = 2 * K - 14
    for n, (chs, rd, wr) in {'ch': ([K], None, None), 'rd': ([], s, None), 'ch_rd': ([K], s, None), 'ch_rd2': ([K], s + 2, None),
                              'wr': ([], None, s), 'ch_wr': ([K], None, s), 'ch_wr2': ([K], None, s + 2)}.items():
        name = f'k{K}_{n}'
        open(f'tests/hw/collide/mpro_{name}.bin', 'wb').write(prog(rd, wr))
        regs = [(0x3204, 32)]
        for c in chs: regs += chan(c)
        for k in ('nop', 'rsh', 'ldr', 'str'):
            for it in (64, 576):
                lines += [f'job {name}_{k}_n{it} 2000 3', f'load 0 ../build/hw/arm/k_dspmem_{k}.bin', 'load 0x1FE000 ../build/hw/arm/stub.bin',
                          f'load 0x20000 tests/hw/collide/mpro_{name}.bin', 'load 0x180000 tests/hw/collide/chan_ramp.bin',
                          'load 0x1C0000 tests/hw/collide/dsp_data.bin', f'word 0x20 {it}', 'quiet']
                lines += [f'areg 0x{a:04X} 0x{v:04X}' for (a, v) in regs]
                lines += ['read 0x1FF100 8', 'read 0x1C0040 4', 'run']
open('tests/hw/collide/jobs.txt', 'w').write('\n'.join(lines) + '\n')
